import { faker } from '@faker-js/faker/locale/pt_BR';

const materiasTecnologia = [
  "Introdução à Computação",
  "Fundamentos de Tecnologia da Informação",
  "Lógica de Programação",
  "Algoritmos e Estruturas de Dados",
  "Programação Orientada a Objetos",
  "Programação Estruturada",
  "Programação Funcional",
  "Engenharia de Software",
  "Análise de Sistemas",
  "Arquitetura de Software",
  "Arquitetura de Computadores",
  "Sistemas Operacionais",
  "Redes de Computadores",
  "Administração de Redes",
  "Segurança da Informação",
  "Criptografia",
  "Cibersegurança",
  "Ethical Hacking",
  "Computação em Nuvem",
  "Computação Distribuída",
  "Sistemas Distribuídos",
  "Internet das Coisas",
  "Computação Móvel",
  "Desenvolvimento Web",
  "Desenvolvimento Front-End",
  "Desenvolvimento Back-End",
  "Desenvolvimento Full Stack",
  "Desenvolvimento de Aplicativos Mobile",
  "Desenvolvimento para Android",
  "Desenvolvimento para iOS",
  "Desenvolvimento de APIs",
  "Desenvolvimento de Microsserviços",
  "Desenvolvimento de Jogos",
  "Programação para Dispositivos Móveis",
  "Interfaces e Experiência do Usuário",
  "Design de Interfaces",
  "UX Design",
  "UI Design",
  "Interação Humano-Computador",
  "Usabilidade de Sistemas",
  "Banco de Dados",
  "Modelagem de Dados",
  "Banco de Dados Relacional",
  "Banco de Dados NoSQL",
  "Administração de Banco de Dados",
  "SQL e Linguagem de Consulta",
  "Data Warehouse",
  "Business Intelligence",
  "Big Data",
  "Engenharia de Dados",
  "Ciência de Dados",
  "Análise de Dados",
  "Visualização de Dados",
  "Mineração de Dados",
  "Estatística Aplicada à Computação",
  "Inteligência Artificial",
  "Fundamentos de Inteligência Artificial",
  "Aprendizado de Máquina",
  "Aprendizado Profundo",
  "Redes Neurais Artificiais",
  "Processamento de Linguagem Natural",
  "Visão Computacional",
  "Robótica",
  "Computação Cognitiva",
  "IA Generativa",
  "Engenharia de Prompt",
  "DevOps",
  "Integração Contínua e Entrega Contínua",
  "Automação de Software",
  "Containers e Docker",
  "Kubernetes",
  "Arquitetura de Sistemas",
  "Arquitetura de Soluções",
  "Qualidade de Software",
  "Testes de Software",
  "Testes Automatizados",
  "Garantia da Qualidade de Software",
  "Gestão de Configuração de Software",
  "Controle de Versão",
  "Git e GitHub",
  "Metodologias Ágeis",
  "Scrum",
  "Kanban",
  "Gestão de Projetos de TI",
  "Governança de TI",
  "Gestão de Serviços de TI",
  "ITIL",
  "Gestão de Riscos em TI",
  "Auditoria de Sistemas",
  "Ética e Legislação em Tecnologia",
  "Empreendedorismo em Tecnologia",
  "Gestão da Inovação",
  "Transformação Digital",
  "Tecnologia e Sociedade",
  "Projeto Integrador em Tecnologia",
  "Projeto de Sistemas",
  "Trabalho de Conclusão de Curso",
  "Estágio Supervisionado em Tecnologia"
];
const sortearNome = () => faker.helpers.arrayElement(materiasTecnologia);

const gerarCodigo = () => faker.helpers.fromRegExp(/[A-Z]{3}[0-9]{3}/);

const gerarCargaHoraria = () => faker.number.int({ min: 60, max: 140, multipleOf: 20 });

export const gerarMateria = (sobrescritas = {}) => ({
    nome: sortearNome(),
    codigo: gerarCodigo(),
    cargaHoraria: gerarCargaHoraria(),
    ...sobrescritas
});
